[phases.setup]

[phases.build]
# Run prisma generate then next build
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "npx prisma db push --skip-generate && npm run start"

[variables]
NODE_ENV = "production"
