[phases.setup]

[phases.build]
# Run prisma generate then next build
cmds = ["prisma generate", "next build"]

[start]
cmd = "npx prisma db push --skip-generate && npm start"

[variables]
NODE_ENV = "production"
